const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const allProducts = [
  // ─── CROP GROWTH ───────────────────────────────────────────────
  {
    id: 'npk-fertilizer',
    name: 'NPK Fertilizer',
    price: 1450,
    originalPrice: 1800,
    image: '/images/product-npk.jpg',
    category: ['all', 'best-sellers', 'crop-growth'],
    tag: 'Complete nutrition for all crops',
    description: 'Balanced macro-nutrient blend with Nitrogen, Phosphorus & Potassium. Suitable for all soil types and crop stages.',
    rating: 4.8,
    reviews: 342,
    badge: 'hot',
    unit: '50 kg bag',
    stock: 50,
  },
  {
    id: 'urea-46',
    name: 'Urea 46',
    price: 980,
    image: '/images/product-urea.jpg',
    category: ['all', 'best-sellers', 'crop-growth'],
    tag: 'High-nitrogen for rapid growth',
    description: 'Premium granular urea with 46% nitrogen content. Ideal for boosting vegetative growth in wheat, paddy, and cotton.',
    rating: 4.7,
    reviews: 289,
    unit: '50 kg bag',
    stock: 100,
  },
  {
    id: 'potassium-complex',
    name: 'Potassium Complex',
    price: 1680,
    originalPrice: 2100,
    image: '/images/product-potassium.jpg',
    category: ['all', 'new-arrivals', 'crop-growth'],
    tag: 'Disease resistance booster',
    description: 'High-potassium formulation that strengthens cell walls, improves drought tolerance, and boosts disease resistance.',
    rating: 4.9,
    reviews: 156,
    badge: 'new',
    unit: '25 kg bag',
    stock: 30,
  },
  {
    id: 'dap',
    name: 'DAP (Di-Ammonium Phosphate)',
    price: 1550,
    originalPrice: 1900,
    image: '/images/product-npk.jpg',
    category: ['all', 'best-sellers', 'crop-growth'],
    tag: 'Best starter fertilizer for all crops',
    description: 'High phosphorus content (46% P\u2082O\u2085) and 18% nitrogen. Excellent starter fertilizer applied at sowing for strong root establishment.',
    rating: 4.8,
    reviews: 412,
    badge: 'hot',
    unit: '50 kg bag',
    stock: 80,
  },
  {
    id: 'calcium-nitrate',
    name: 'Calcium Nitrate',
    price: 1180,
    image: '/images/product-urea.jpg',
    category: ['all', 'specialty', 'crop-growth'],
    tag: 'Fast-acting nitrogen + calcium',
    description: 'Water-soluble calcium nitrate provides immediately available nitrogen and calcium for fertigation use in fruits and vegetables.',
    rating: 4.6,
    reviews: 143,
    unit: '25 kg bag',
    stock: 45,
  },
  {
    id: 'ammonium-sulphate',
    name: 'Ammonium Sulphate',
    price: 890,
    image: '/images/product-sulphur.jpg',
    category: ['all', 'crop-growth'],
    tag: 'Nitrogen & sulphur for quality grain',
    description: 'Provides 21% nitrogen and 24% sulphur. Ideal for oilseeds, pulses, and crops in sulphur-deficient soils.',
    rating: 4.5,
    reviews: 201,
    unit: '50 kg bag',
    stock: 60,
  },
  {
    id: 'map',
    name: 'MAP (Mono Ammonium Phosphate)',
    price: 1620,
    image: '/images/product-phosphate.jpg',
    category: ['all', 'specialty', 'crop-growth'],
    tag: 'High-purity water-soluble phosphorus',
    description: 'Contains 61% P\u2082O\u2085 and 12% nitrogen. Highly water-soluble and ideal for drip irrigation and fertigation systems.',
    rating: 4.7,
    reviews: 118,
    badge: 'new',
    unit: '25 kg bag',
    stock: 25,
  },
  {
    id: 'boron-fertilizer',
    name: 'Boron Fertilizer',
    price: 1340,
    image: '/images/product-micronutrient.jpg',
    category: ['all', 'specialty', 'crop-growth'],
    tag: 'Improves fruit set and seed quality',
    description: 'Soluble boron (20.5% B) for foliar or soil application. Essential for pollination, fruit set, and seed development in horticulture crops.',
    rating: 4.5,
    reviews: 89,
    unit: '1 kg pack',
    stock: 120,
  },

  // ─── SOIL HEALTH ───────────────────────────────────────────────
  {
    id: 'phosphate-mix',
    name: 'Phosphate Mix',
    price: 1250,
    image: '/images/product-phosphate.jpg',
    category: ['all', 'organic', 'soil-health'],
    tag: 'Strong root development',
    description: 'Single superphosphate blended with organic matter to enhance phosphorus availability and promote deep root systems.',
    rating: 4.6,
    reviews: 198,
    unit: '50 kg bag',
    stock: 65,
  },
  {
    id: 'organic-compost-plus',
    name: 'Organic Compost Plus',
    price: 850,
    image: '/images/product-organic.jpg',
    category: ['all', 'organic', 'new-arrivals', 'soil-health'],
    tag: '100% natural ingredients',
    description: 'Enriched vermicompost with beneficial microbes, humic acid, and plant growth hormones for long-term soil fertility improvement.',
    rating: 4.8,
    reviews: 267,
    badge: 'new',
    unit: '30 kg bag',
    stock: 150,
  },
  {
    id: 'sulphur-granules',
    name: 'Sulphur Granules',
    price: 1100,
    originalPrice: 1350,
    image: '/images/product-sulphur.jpg',
    category: ['all', 'specialty', 'soil-health'],
    tag: 'Soil pH correction',
    description: 'Elemental sulphur (90%) in easy-to-apply granular form. Lowers pH in alkaline soils and provides sulphur nutrition for oilseeds.',
    rating: 4.4,
    reviews: 98,
    badge: 'sale',
    unit: '25 kg bag',
    stock: 40,
  },
  {
    id: 'zinc-sulphate',
    name: 'Zinc Sulphate',
    price: 1320,
    image: '/images/product-zinc.jpg',
    category: ['all', 'specialty', 'best-sellers', 'soil-health'],
    tag: 'Zinc deficiency treatment',
    description: 'Zinc sulphate monohydrate (33% Zn) corrects zinc deficiency in rice, wheat, and maize. Enhances enzyme activity and grain filling.',
    rating: 4.6,
    reviews: 176,
    unit: '25 kg bag',
    stock: 55,
  },
  {
    id: 'micronutrient-blend',
    name: 'Micronutrient Blend',
    price: 2200,
    image: '/images/product-micronutrient.jpg',
    category: ['all', 'specialty', 'soil-health'],
    tag: 'Essential trace elements',
    description: 'Multi-micronutrient formula with Zn, B, Fe, Mn, Cu & Mo. Designed for soil drenching to address complex deficiencies.',
    rating: 4.5,
    reviews: 124,
    unit: '5 kg bag',
    stock: 20,
  },
  {
    id: 'gypsum-powder',
    name: 'Gypsum Powder',
    price: 680,
    image: '/images/product-sulphur.jpg',
    category: ['all', 'soil-health', 'organic'],
    tag: 'Improves soil structure & drainage',
    description: 'Agricultural gypsum (calcium sulphate) that improves clay soil structure, reduces compaction, and provides calcium and sulphur nutrition.',
    rating: 4.3,
    reviews: 154,
    unit: '50 kg bag',
    stock: 200,
  },
  {
    id: 'humic-acid-granules',
    name: 'Humic Acid Granules',
    price: 1780,
    originalPrice: 2200,
    image: '/images/product-organic.jpg',
    category: ['all', 'organic', 'new-arrivals', 'soil-health'],
    tag: 'Enhances nutrient uptake & water retention',
    description: 'High-purity humic acid (85%) derived from leonardite. Improves cation exchange capacity, water holding capacity and microbial activity.',
    rating: 4.7,
    reviews: 93,
    badge: 'sale',
    unit: '5 kg bag',
    stock: 35,
  },
  {
    id: 'bio-fertilizer',
    name: 'Bio Fertilizer (Rhizobium)',
    price: 420,
    image: '/images/product-organic.jpg',
    category: ['all', 'organic', 'soil-health'],
    tag: 'Natural nitrogen fixation for legumes',
    description: 'Live rhizobium bacterial culture for seed treatment in legumes (soybean, groundnut, chickpea). Fixes atmospheric nitrogen and reduces urea requirement.',
    rating: 4.6,
    reviews: 207,
    badge: 'new',
    unit: '200 g pack',
    stock: 90,
  },
  {
    id: 'vermicompost',
    name: 'Premium Vermicompost',
    price: 560,
    image: '/images/product-organic.jpg',
    category: ['all', 'organic', 'soil-health'],
    tag: 'Rich in organic matter & earthworm cast',
    description: 'Certified organic vermicompost rich in humus, beneficial microorganisms and plant-available nutrients for vegetable and fruit crops.',
    rating: 4.8,
    reviews: 318,
    unit: '25 kg bag',
    stock: 120,
  },
];

async function main() {
  for (const product of allProducts) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: product,
      create: product,
    });
  }
  console.log('Seeded completely!');
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
